### ISSUE TITLE
Is there any way to see the log of the failed evaluation?

### ISSUE THREAD

**Issue by Anothorld** [Drdestiny/DeeperForensicsChallengeSubmissionExample#2]
My docker runs well locally but failed on the server.

**Comment by ljj898** [comment]
metoo!!
how did you solve it ?

**Comment by Anothorld** [comment]
> metoo!!
> how did you solve it ?

I found it was a TypeError in my code, I changed the default output type of detector from float to torch.Tensor.
but it failed again even after I fix the TypeError

**Comment by ljj898** [comment]
ME too!!!
thanks for you reply very much
I also failed first time because of this problem but when I fixed it&nbsp; failed again&nbsp;
so by now did you solve the second problem????




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Drdestiny/DeeperForensicsChallengeSubmissionExample"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月19日(星期六) 下午5:30
收件人:&nbsp;"Drdestiny/DeeperForensicsChallengeSubmissionExample"<DeeperForensicsChallengeSubmissionExample@noreply.github.com&gt;;
抄送:&nbsp;"Rice &amp; Shine"<1140801877@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Drdestiny/DeeperForensicsChallengeSubmissionExample] Is there any way to see the log of the failed evaluation? (#2)





  
metoo!!
 how did you solve it ?
  
I found it was a TypeError in my code, I used changed the default output type of detector from float to torch.Tensor.
 but it failed again even after I fix the TypeError

**Comment by Drdestiny** [comment]
> I found it was a TypeError in my code, I changed the default output type of detector from float to torch.Tensor.
> but it failed again even after I fix the TypeError

It seems you haven't built a new Docker image after you changed your code?

**Comment by ljj898** [comment]
emm，but I did make new docker images several times. do you mean make new images with a different name from first one？



---Original---

**Comment by Anothorld** [comment]
I did rebuild my Docker after I changed my code, but it still didn't work. I'm checking my frame extractor and the face detector. maybe there' some bugs inside them. I'm wondering if there is any test video contained more than one face? My extractor only works when there is only one face in the video.

**Comment by Drdestiny** [comment]
Have you tried `docker run -it --rm --gpus all <image-name> python local_test.py`? Running in local environment is different from running in Docker image because you might not install dependencies in Dockerfile.

**Comment by ljj898** [comment]
A little difference.
I tried like this:
docker run -it --gpus all <image-name&gt; python local_test.py?

without&nbsp; ——rm

---Original---

**Comment by Anothorld** [comment]
yes, I use `docker run` locally after I rebuild it.

**Comment by Drdestiny** [comment]
>A little difference.
> I tried like this:
> docker run -it --gpus all <image-name&gt; python local_test.py?

>without&nbsp; ——rm

That's okay. `--rm` just deletes this container after running.

**Comment by EndlessSora** [comment]
> I did rebuild my Docker after I changed my code, but it still didn't work. I'm checking my frame extractor and the face detector. maybe there' some bugs inside them. I'm wondering if there is any test video contained more than one face? My extractor only works when there is only one face in the video.

I think making your extractor robust to diverse situations is a good choice. :-)

**Comment by Drdestiny** [comment]
Please give us your email account.

**Comment by ljj898** [comment]
030849093930



---Original---

**Comment by Anothorld** [comment]
> > I did rebuild my Docker after I changed my code, but it still didn't work. I'm checking my frame extractor and the face detector. maybe there' some bugs inside them. I'm wondering if there is any test video contained more than one face? My extractor only works when there is only one face in the video.
> 
> I think making your extractor robust to diverse situations is a good choice. :-)

thank you, I'll try to make it more robust.

**Comment by Anothorld** [comment]
811370425750

**Comment by Drdestiny** [comment]
> 811370425750

Anothorld, the reason is timeout, not bug.

**Comment by Drdestiny** [comment]
> 030849093930

ljj898, the log of your submission is like this:
```
Traceback (most recent call last):
File "run_evaluation.py", line 80, in <module>
evaluate_runtime(start_time, DeeperForensicsDetector, deeper_forensics_frames_iter, job_name)
File "run_evaluation.py", line 53, in evaluate_runtime
prob = detector.predict(frames)
File "model/toy_predict.py", line 12, in predict
result = super(FakePredictor, self).predict(video_frames)
File "/workspace/DeeperForensics_Eval/eval_kit/detector.py", line 84, in predict
probability = self.process_video(video_frames)
File "/workspace/DeeperForensics_Eval/eval_kit/detector.py", line 58, in process_video
return prob
UnboundLocalError: local variable 'prob' referenced before assignment
```

**Comment by xstju** [comment]
> Have you tried `docker run -it --rm --gpus all <image-name> python local_test.py`? Running in local environment is different from running in Docker image because you might not install dependencies in Dockerfile.

I have meet the same problem,  My docker runs well locally but failed on the server. 
I have tried docker run -it --rm --gpus all <image-name> python local_test.py .  It  is  well.
So can you  provide the log of my submission？
My  aws-id 334889259927
Thank you
